/*NIM GAME-->>IS GAME ME DO LOG KHLETE HAIN AUR
AUR EK NO DIYA HOTA HAI AUR DONO ME SE JO US NO
KO PALE BOLDEGA VO JEET JAYEGA AUR START ONE SE
 HOGA AUR  AAP AK BAS=R ME KWA3 NO HI BOL SAKTE
 HAIN . */
/*IS GAME ME YADI DIYE HUE NO SE JO BHI 4 KA FATOR
HOGA PAS MEUSKE ACCORDING HAM START KAR DENGE AUR  DIYA HUA NO 4 KA FACTOR HAITO JO PAHLE START KAREGA
VO JAROOR HAREGA*/
/*AUR YEY BHI DHYAN RKHNA HOGA KI JITNE KE LIYE JO 4 KA FACTOR 
PAS ME HOGA AUR JITNA KAM HOGA START URNE SE HI KRNA HOGA
FOR EXAMPLE-->>N=23 THEN 20 NEAREST 4 FAACTOR 
THEN START FROM 123 */
//AUR HAME START KRNE KE BAD HAMESHA 4 KA GAP MAINTAIN KRNA 
//PADEGA YADI V0 1 LEGA TO HME 3 LENA PADEGA 2+2,3+1,1+3
#include <iostream>
using namespace std;
int main()
{
    int n;
    cout << "Enter value of n:";
    cin >> n;
if(n%4!=0) cout<<"Win";
else cout<<"loos";
   // return 0;
}